### ISSUE TITLE
Status-synchronization between Jira and csa/dashboard is broken

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-dashboard#162]
[This issue is imported from pivotal - Originaly created at Jun 11, 2015 by Okke Harsta](https://www.pivotaltracker.com/story/show/96780000)

In dashboard, some issues are shown with incorrect status.

**Comment by phavekes** [comment]
It appears that any transition other than to the status \'closed\' is ignored by design.

@hennybekker if you simply make sure that you \'close\' issues that are done, they should indeed update. (Hans Westerbeek - Jun 18, 2015)

**Comment by phavekes** [comment]
Hmmm....  Het op "RESOLVED" (not closed) plaatsen van het ticket "TEST-2414" in JIRA maakt dat bij een reload van Dashboard de error:
"Er is iets misgegaan tijdens het openen van de pagina.
Probeer het later nog eens of neem contract op met support@surfconext.nl."
getoond wordt :-(
De andere functies zijn wel toegankelijk..

De logfile toont o.a.:
---------
2015-09-23 13:46:46,742 ERROR [http-nio-9191-exec-4] selfservice.api.rest.ExceptionLogger:17 - Unexpected exception occurred
org.springframework.web.client.HttpClientErrorException: 409 Conflict
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91) ~[spring-web-4.1.6.RELEASE.jar!/:4.1.6.RELEASE]
        at org.springframework.security.oauth2.client.http.OAuth2ErrorHandler.handleError(OAuth2ErrorHandler.java:165) ~[spring-security-oauth2-2.0.7.RELEASE.jar!/:na]
--------- (Henny Bekker - Sep 23, 2015)

**Comment by phavekes** [comment]
Hmmm...  Is opgelost door het ticket echt te "sluiten" (Closed met status code done) (Henny Bekker - Sep 23, 2015)
